
services:
  mySql1:
    image: mysql:latest
    container_name: mySql1
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: end2end_llb

  mySql2:
    image: mysql:latest
    container_name: mySql2
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: end2end_llb

  SpringServer1:
    image: prithivi97/syncrepo:springserver1
    container_name: SpringServer1
    ports:
      - "8080:8080"
    depends_on:
      - mySql1
    restart: on-failure

  SpringServer2:
    image: prithivi97/syncrepo:springserver2
    container_name: SpringServer2
    ports:
      - "8081:8081"
    depends_on:
      - mySql2
    restart: on-failure
